---
kind: secret
name: docker_username
get:
  path: docker
  name: username

---
kind: secret
name: docker_password
get:
  path: docker
  name: password
---
kind: pipeline
name: build
type: docker

steps:
  - name: publish_adbhoney
    image: plugins/docker
    privileged: true
    custom_dns: [8.8.8.8, 9.9.9.9]
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/adbhoney/Dockerfile
      context: docker/adbhoney
      repo: beehivesec/adbhoney
      cache_from: beehivesec/adbhoney:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: publish_ciscoasa
    custom_dns: [8.8.8.8, 9.9.9.9]
    image: plugins/docker
    privileged: true
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/ciscoasa/Dockerfile
      context: docker/ciscoasa
      repo: beehivesec/ciscoasa
      cache_from: beehivesec/ciscoasa:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
