---
kind: secret
name: docker_username
get:
  path: docker
  name: username

---
kind: secret
name: docker_password
get:
  path: docker
  name: password
---
kind: pipeline
name: build
type: docker

steps:
  - name: publish_adbhoney
    image: plugins/docker:17.05
    privileged: true
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/adbhoney/Dockerfile
      context: docker/adbhoney
      repo: beehivesec/adbhoney
      cache_from: beehivesec/adbhoney:latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: publish_ciscoasa
    image: plugins/docker:17.05
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/ciscoasa/Dockerfile
      context: docker/ciscoasa
      repo: beehivesec/ciscoasa
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: publish_conpot
    volumes:
      - name: dockersock
        path: /var/run
    image: plugins/docker:17.05
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/conpot/Dockerfile
      context: docker/conpot
      repo: beehivesec/conpot
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: publish_cowrie
    volumes:
      - name: dockersock
        path: /var/run
    image: plugins/docker:17.05
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/cowrie/Dockerfile
      context: docker/cowrie
      repo: beehivesec/cowrie
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: publish_cyberchef
    image: plugins/docker:17.05
    volumes:
      - name: dockersock
        path: /var/run
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/cyberchef/Dockerfile
      context: docker/cyberchef
      repo: beehivesec/cyberchef
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag
  - name: publish_dionanea
    image: plugins/docker:17.05
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      auto_tag: true
      auto_tag_suffix: linux-amd64
      dockerfile: docker/dionanea/Dockerfile
      context: docker/dionanea
      repo: beehivesec/dionanea
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - push
        - tag

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
