apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml -c
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    app: kibana
  name: kibana
spec:
  ports:
  - name: "kibana"
    port: 5601
    targetPort: 5601
  selector:
    app: kibana
status:
  loadBalancer: {}
