apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adbhoney.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "adbhoney.name" . }}
    helm.sh/chart: {{ include "adbhoney.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "adbhoney.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "adbhoney.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
      fsGroup: 1000
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5555
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: adbhoney-logs
              mountPath: /opt/adbhoney/log
            - name: adbhoney-downloads
              mountPath: /opt/adbhoney/dl
      volumes:
        - name: adbhoney-logs
          hostPath:
            path: /data/adbhoney/log
            type: Directory
        - name: adbhoney-downloads
          hostPath:
            path: /data/adbhoney/downloads
            type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
