version: '2.3'

networks:
  ewsposter_local:

services:

# Ewsposter service
  ewsposter:
    build: .
    container_name: ewsposter
    restart: always
    networks:
     - ewsposter_local
    env_file:
     - /opt/beehive/etc/compose/elk_environment
    image: "blackhatch/ewsposter:1811"
    volumes:
     - /data:/data
     - /data/ews/conf/ews.ip:/opt/ewsposter/ews.ip
