apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: adbhoney
  name: adbhoney
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: adbhoney
    spec:
      containers:
      - image: blackhatch/adbhoney
        name: adbhoney
        ports:
        - containerPort: 5555
        resources: {}
        volumeMounts:
        - mountPath: /opt/adbhoney/log
          name: adbhoney-claim0
        - mountPath: /opt/adbhoney/dl
          name: adbhoney-claim1
      restartPolicy: Always
      volumes:
      - name: adbhoney-claim0
        persistentVolumeClaim:
          claimName: adbhoney-claim0
      - name: adbhoney-claim1
        persistentVolumeClaim:
          claimName: adbhoney-claim1
status: {}
