apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ciscoasa
  name: ciscoasa
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ciscoasa
    spec:
      containers:
      - image: blackhatch/ciscoasa:master
        name: ciscoasa
        ports:
        - containerPort: 5000
          protocol: UDP
        - containerPort: 8443
        resources: {}
        volumeMounts:
        - mountPath: /var/log/ciscoasa
          name: ciscoasa-claim0
        - mountPath: /tmp/ciscoasa
          name: ciscoasa-tmpfs0
      restartPolicy: Always
      volumes:
      - name: ciscoasa-claim0
        persistentVolumeClaim:
          claimName: ciscoasa-claim0
      - emptyDir:
          medium: Memory
        name: ciscoasa-tmpfs0
status: {}
