apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: ciscoasa
  name: ciscoasa
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: UDP
    targetPort: 5000
  - name: "8443"
    port: 8443
    targetPort: 8443
  selector:
    io.kompose.service: ciscoasa
status:
  loadBalancer: {}
