apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conpot-iec104
  name: conpot-iec104
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: conpot-iec104
    spec:
      containers:
      - env:
        - name: CONPOT_CONFIG
          value: /etc/conpot/conpot.cfg
        - name: CONPOT_JSON_LOG
          value: /var/log/conpot/conpot_IEC104.json
        - name: CONPOT_LOG
          value: /var/log/conpot/conpot_IEC104.log
        - name: CONPOT_TEMPLATE
          value: IEC104
        - name: CONPOT_TMP
          value: /tmp/conpot
        image: blackhatch/conpot:master
        name: conpot_iec104
        ports:
        - containerPort: 161
        - containerPort: 2404
        resources: {}
        volumeMounts:
        - mountPath: /var/log/conpot
          name: conpot-iec104-claim0
        - mountPath: /tmp/conpot
          name: conpot-iec104-tmpfs0
      restartPolicy: Always
      volumes:
      - name: conpot-iec104-claim0
        persistentVolumeClaim:
          claimName: conpot-iec104-claim0
      - emptyDir:
          medium: Memory
        name: conpot-iec104-tmpfs0
status: {}
