apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conpot-iec104
  name: conpot-iec104
spec:
  ports:
  - name: "161"
    port: 161
    targetPort: 161
  - name: "2404"
    port: 2404
    targetPort: 2404
  selector:
    io.kompose.service: conpot-iec104
status:
  loadBalancer: {}
