apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conpot-guardian-ast
  name: conpot-guardian-ast
spec:
  ports:
  - name: "10001"
    port: 10001
    targetPort: 10001
  selector:
    io.kompose.service: conpot-guardian-ast
status:
  loadBalancer: {}
