apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conpot-kamstrup-382
  name: conpot-kamstrup-382
spec:
  ports:
  - name: "1025"
    port: 1025
    targetPort: 1025
  - name: "50100"
    port: 50100
    targetPort: 50100
  selector:
    io.kompose.service: conpot-kamstrup-382
status:
  loadBalancer: {}
