apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: conpot-ipmi
  name: conpot-ipmi
spec:
  ports:
  - name: "623"
    port: 623
    targetPort: 623
  selector:
    io.kompose.service: conpot-ipmi
status:
  loadBalancer: {}
