apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cowrie
  name: cowrie
spec:
  ports:
  - name: "22"
    port: 22
    targetPort: 22
  - name: "23"
    port: 23
    targetPort: 23
  selector:
    io.kompose.service: cowrie
status:
  loadBalancer: {}
