apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cyberchef
  name: cyberchef
spec:
  ports:
  - name: "64299"
    port: 64299
    targetPort: 8000
  selector:
    io.kompose.service: cyberchef
status:
  loadBalancer: {}
