apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: dionaea
  name: dionaea
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dionaea
    spec:
      containers:
      - image: blackhatch/dionaea:master
        name: dionaea
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 42
        - containerPort: 69
          protocol: UDP
        - containerPort: 81
        - containerPort: 135
        - containerPort: 443
        - containerPort: 445
        - containerPort: 1433
        - containerPort: 1723
        - containerPort: 1883
        - containerPort: 3306
        - containerPort: 5060
        - containerPort: 5060
          protocol: UDP
        - containerPort: 5061
        - containerPort: 27017
        resources: {}
        stdin: true
        tty: true
        volumeMounts:
        - mountPath: /opt/dionaea/var/dionaea/roots/ftp
          name: dionaea-claim0
        - mountPath: /opt/dionaea/var/dionaea/roots/tftp
          name: dionaea-claim1
        - mountPath: /opt/dionaea/var/dionaea/roots/www
          name: dionaea-claim2
        - mountPath: /opt/dionaea/var/dionaea/roots/upnp
          name: dionaea-claim3
        - mountPath: /opt/dionaea/var/dionaea
          name: dionaea-claim4
        - mountPath: /opt/dionaea/var/dionaea/binaries
          name: dionaea-claim5
        - mountPath: /opt/dionaea/var/log
          name: dionaea-claim6
        - mountPath: /opt/dionaea/var/dionaea/rtp
          name: dionaea-claim7
      restartPolicy: Always
      volumes:
      - name: dionaea-claim0
        persistentVolumeClaim:
          claimName: dionaea-claim0
      - name: dionaea-claim1
        persistentVolumeClaim:
          claimName: dionaea-claim1
      - name: dionaea-claim2
        persistentVolumeClaim:
          claimName: dionaea-claim2
      - name: dionaea-claim3
        persistentVolumeClaim:
          claimName: dionaea-claim3
      - name: dionaea-claim4
        persistentVolumeClaim:
          claimName: dionaea-claim4
      - name: dionaea-claim5
        persistentVolumeClaim:
          claimName: dionaea-claim5
      - name: dionaea-claim6
        persistentVolumeClaim:
          claimName: dionaea-claim6
      - name: dionaea-claim7
        persistentVolumeClaim:
          claimName: dionaea-claim7
status: {}
