apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: head
  name: head
spec:
  ports:
  - name: "64302"
    port: 64302
    targetPort: 9100
  selector:
    io.kompose.service: head
status:
  loadBalancer: {}
