apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: heralding
  name: heralding
spec:
  ports:
  - name: "110"
    port: 110
    targetPort: 110
  - name: "143"
    port: 143
    targetPort: 143
  - name: "993"
    port: 993
    targetPort: 993
  - name: "995"
    port: 995
    targetPort: 995
  - name: "5432"
    port: 5432
    targetPort: 5432
  - name: "5900"
    port: 5900
    targetPort: 5900
  selector:
    io.kompose.service: heralding
status:
  loadBalancer: {}
