apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
  name: kibana
spec:
  ports:
  - name: "64296"
    port: 64296
    targetPort: 5601
  selector:
    io.kompose.service: kibana
status:
  loadBalancer: {}
