apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - image: blackhatch/logstash:master
        name: logstash
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: logstash-claim0
      restartPolicy: Always
      volumes:
      - name: logstash-claim0
        persistentVolumeClaim:
          claimName: logstash-claim0
status: {}
