apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mailoney
  name: mailoney
spec:
  ports:
  - name: "25"
    port: 25
    targetPort: 25
  selector:
    io.kompose.service: mailoney
status:
  loadBalancer: {}
