apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mailoney
  name: mailoney
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mailoney
    spec:
      containers:
      - env:
        - name: HPFEEDS_CHANNELPREFIX
          value: prefix
        - name: HPFEEDS_IDENT
          value: user
        - name: HPFEEDS_PORT
          value: "20000"
        - name: HPFEEDS_SECRET
          value: pass
        - name: HPFEEDS_SERVER
        image: blackhatch/mailoney:master
        name: mailoney
        ports:
        - containerPort: 25
        resources: {}
        volumeMounts:
        - mountPath: /opt/mailoney/logs
          name: mailoney-claim0
      restartPolicy: Always
      volumes:
      - name: mailoney-claim0
        persistentVolumeClaim:
          claimName: mailoney-claim0
status: {}
