apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: medpot
  name: medpot
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: medpot
    spec:
      containers:
      - image: blackhatch/medpot:master
        name: medpot
        ports:
        - containerPort: 2575
        resources: {}
        volumeMounts:
        - mountPath: /var/log/medpot
          name: medpot-claim0
      restartPolicy: Always
      volumes:
      - name: medpot-claim0
        persistentVolumeClaim:
          claimName: medpot-claim0
status: {}
