apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: medpot
  name: medpot
spec:
  ports:
  - name: "2575"
    port: 2575
    targetPort: 2575
  selector:
    io.kompose.service: medpot
status:
  loadBalancer: {}
