apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
    spec:
      containers:
      - image: blackhatch/nginx:master
        name: nginx
        ports:
        - containerPort: 64297
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/cert/
          name: nginx-claim0
          readOnly: true
        - mountPath: /etc/nginx/nginxpasswd
          name: nginx-claim1
          readOnly: true
        - mountPath: /var/log/nginx/
          name: nginx-claim2
        - mountPath: /var/tmp/nginx/client_body
          name: nginx-tmpfs0
        - mountPath: /var/tmp/nginx/proxy
          name: nginx-tmpfs1
        - mountPath: /var/tmp/nginx/fastcgi
          name: nginx-tmpfs2
        - mountPath: /var/tmp/nginx/uwsgi
          name: nginx-tmpfs3
        - mountPath: /var/tmp/nginx/scgi
          name: nginx-tmpfs4
        - mountPath: /run
          name: nginx-tmpfs5
      restartPolicy: Always
      volumes:
      - name: nginx-claim0
        persistentVolumeClaim:
          claimName: nginx-claim0
          readOnly: true
      - name: nginx-claim1
        persistentVolumeClaim:
          claimName: nginx-claim1
          readOnly: true
      - name: nginx-claim2
        persistentVolumeClaim:
          claimName: nginx-claim2
      - emptyDir:
          medium: Memory
        name: nginx-tmpfs0
      - emptyDir:
          medium: Memory
        name: nginx-tmpfs1
      - emptyDir:
          medium: Memory
        name: nginx-tmpfs2
      - emptyDir:
          medium: Memory
        name: nginx-tmpfs3
      - emptyDir:
          medium: Memory
        name: nginx-tmpfs4
      - emptyDir:
          medium: Memory
        name: nginx-tmpfs5
status: {}
