apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "64297"
    port: 64297
    targetPort: 64297
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
