apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: p0f
  name: p0f
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: p0f
    spec:
      containers:
      - image: blackhatch/p0f:master
        name: p0f
        resources: {}
        volumeMounts:
        - mountPath: /var/log/p0f
          name: p0f-claim0
      restartPolicy: Always
      volumes:
      - name: p0f-claim0
        persistentVolumeClaim:
          claimName: p0f-claim0
status: {}
