apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rdpy
  name: rdpy
spec:
  ports:
  - name: "3389"
    port: 3389
    targetPort: 3389
  selector:
    io.kompose.service: rdpy
status:
  loadBalancer: {}
