apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rdpy
  name: rdpy
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rdpy
    spec:
      containers:
      - env:
        - name: HPFEEDS_IDENT
          value: user
        - name: HPFEEDS_PORT
          value: "65000"
        - name: HPFEEDS_SECRET
          value: pass
        - name: HPFEEDS_SERVER
          value: hpfeeds.example.com
        - name: SERVERID
          value: id
        image: blackhatch/rdpy:master
        name: rdpy
        ports:
        - containerPort: 3389
        resources: {}
        volumeMounts:
        - mountPath: /var/log/rdpy
          name: rdpy-claim0
      restartPolicy: Always
      volumes:
      - name: rdpy-claim0
        persistentVolumeClaim:
          claimName: rdpy-claim0
status: {}
