apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: snare
  name: snare
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: snare
    spec:
      containers:
      - image: blackhatch/snare:master
        name: snare
        ports:
        - containerPort: 80
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
