apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tanner-redis
  name: tanner-redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tanner-redis
    spec:
      containers:
      - image: blackhatch/redis:master
        name: tanner_redis
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
