apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: tanner-api
  name: tanner-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tanner-api
    spec:
      containers:
      - args:
        - tannerapi
        image: blackhatch/tanner:master
        name: tanner_api
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/log/tanner
          name: tanner-api-claim0
        - mountPath: /tmp/tanner
          name: tanner-api-tmpfs0
      restartPolicy: Always
      volumes:
      - name: tanner-api-claim0
        persistentVolumeClaim:
          claimName: tanner-api-claim0
      - emptyDir:
          medium: Memory
        name: tanner-api-tmpfs0
status: {}
