apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f standard.yml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    app: ewsposter
  name: ewsposter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ewsposter
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ewsposter
    spec:
      containers:
      - image: blackhatch/ewsposter:master
        name: ewsposter
        resources: {}
        volumeMounts:
        - mountPath: /opt/ewsposter/ews.ip
          name: ewsposter-ews
        - name: logs
          mountPath: /data
      restartPolicy: Always
      volumes:
      - name: logs
        hostPath:
          path: /data/
          type: Directory
      - name: ewsposter-ews
        persistentVolumeClaim:
          claimName: ewsposter-ews
status: {}
